#when@prod:
#    api_platform:
#        oauth:
#            enabled: '%oidc.enabled%'
#            clientId: '%oidc.client_id%'
#            # The OAuth client secret.
#            clientSecret: '%oidc.client_secret%'
#
#            # The OAuth type.
#            type: 'oauth2'
#
#            # The OAuth flow grant type.
#            flow: 'authorizationCode'
#
#            # The OAuth token URL. Make sure to check the specification tokenUrl is not needed for an implicit flow.
#            tokenUrl: '%oidc.token_url%'
#
#            # The OAuth authentication URL.
#            authorizationUrl: '%oidc.authorization_url%'
#
#            # The OAuth scopes.
#            #        scopes: [ 'profile', 'email', 'offline_access', 'openid', 'roles', 'groups' ]
#            scopes:
#                profile: 'Access to your profile information'
#                email: 'Access to your email address'
#                offline_access: 'Access to refresh tokens'
#                openid: 'Authenticate using OpenID Connect'
#                roles: 'Access to your roles'

when@test:
    api_platform:
        oauth:
            enabled: false

api_platform:
    title: Download Router
    version: 0.1.2
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        pagination_client_enabled: true
#        pagination_client_partial: true
        pagination_client_items_per_page: true
        maximum_items_per_page: 1000
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            enabled_parameter_name: 'pagination'
#            partial_parameter_name: 'range'
            items_per_page_parameter_name: 'itemsPerPage'
    messenger:
        enabled: true
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        xml: ["application/xml", "text/xml"]
        yaml: ["application/x-yaml"]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

