<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250915111756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE download_job_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, worker_identifier VARCHAR(255) NOT NULL, event VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, update_message VARCHAR(255) DEFAULT NULL, context JSON DEFAULT NULL, metadata JSON DEFAULT NULL, exception_message VARCHAR(255) DEFAULT NULL, download_job_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB780834C918CB82 ON download_job_event (download_job_id)');
        $this->addSql('ALTER TABLE download_job_event ADD CONSTRAINT FK_FB780834C918CB82 FOREIGN KEY (download_job_id) REFERENCES download_job (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE download_pool (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, root_path TEXT NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE download_job_event DROP CONSTRAINT FK_FB780834C918CB82');
        $this->addSql('DROP TABLE download_job_event');
    }
}
