<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311224703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE oidc_subject_identifier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE download_job ADD owner_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE download_job ADD CONSTRAINT FK_D1CE95A57E3C61F9 FOREIGN KEY (owner_id) REFERENCES oidc_subject_identifier (id)');
        $this->addSql('CREATE INDEX IDX_D1CE95A57E3C61F9 ON download_job (owner_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE oidc_subject_identifier');
        $this->addSql('ALTER TABLE download_job DROP CONSTRAINT FK_D1CE95A57E3C61F9');
        $this->addSql('DROP INDEX IDX_D1CE95A57E3C61F9');
        $this->addSql('ALTER TABLE download_job DROP owner_id');
    }
}
