<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250918201357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE downloaded_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path TEXT NOT NULL, metadata JSON NOT NULL, visible BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE downloaded_file_download_job (downloaded_file_id INT NOT NULL, download_job_id INT NOT NULL, PRIMARY KEY (downloaded_file_id, download_job_id))');
        $this->addSql('CREATE INDEX IDX_CFB4E630DB7C2E6C ON downloaded_file_download_job (downloaded_file_id)');
        $this->addSql('CREATE INDEX IDX_CFB4E630C918CB82 ON downloaded_file_download_job (download_job_id)');
        $this->addSql('ALTER TABLE downloaded_file_download_job ADD CONSTRAINT FK_CFB4E630DB7C2E6C FOREIGN KEY (downloaded_file_id) REFERENCES downloaded_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE downloaded_file_download_job ADD CONSTRAINT FK_CFB4E630C918CB82 FOREIGN KEY (download_job_id) REFERENCES download_job (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE downloaded_file_download_job DROP CONSTRAINT FK_CFB4E630DB7C2E6C');
        $this->addSql('ALTER TABLE downloaded_file_download_job DROP CONSTRAINT FK_CFB4E630C918CB82');
        $this->addSql('DROP TABLE downloaded_file');
        $this->addSql('DROP TABLE downloaded_file_download_job');
    }
}
