### Create a new download job with minimal payload
POST {{ client.host }}/download_jobs
Content-Type: application/ld+json

{
    "uri": "https://example.com"
}

### Create a new download job with user agent
POST {{ client.host }}/download_jobs
Content-Type: application/ld+json

{
  "uri": "https://example.com",
  "userAgent": "string"
}

### Create a new download job with cookies
POST {{ client.host }}/download_jobs
Content-Type: application/ld+json

{
  "uri": "https://example.com",
  "userAgent": "string",
  "cookies": [
    "key=value",
    "key2=value2"
  ]
}

### Create a new download job with full payload
POST {{ client.host }}/download_jobs
Content-Type: application/ld+json

{
  "uri": "https://example.com",
  "userAgent": "string",
  "cookies": [
    "string"
  ],
  "downloader": "mock"
}

### Metube example
POST {{ client.host }}/add
Content-Type: application/json

{
    "quality":"best",
    "format":"any",
    "url":"https://civitai.com/images/99758635",
    "auto_start":true
}

### Civitai post example
POST {{ client.host }}/add
Content-Type: application/json

{
    "quality":"best",
    "format":"any",
    "url":"https://civitai.com/posts/20880106",
    "auto_start":true
}

### Create a new download job for a supported, but not yet whitelisted domain
POST {{ client.host }}/add
Content-Type: application/json

{
    "quality":"best",
    "format":"any",
    "url":"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "auto_start":true
}
